name: Test 2

on:
  pull_request:

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  test2:
    name: Lint Python files
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: echo "hi"
